### ISSUE TITLE
Please provide some sort of build or getting started instructions

### ISSUE THREAD

**Issue by ridiculousfish** [mattdesl/three-line-2d#5]
This is surely obvious to users steeped in the npm ecosystem, but I am totally new to npm and quickly got lost trying to do anything with this package.
1. Click on the [test.js](https://github.com/mattdesl/three-line-2d/blob/master/test/test.js) link from the README.md hoping for a complete example.

Result: broken link.
1. Try `npm install mattdesl/three-line-2d`. This looks promising: I get some files.
2. Try `open node_modules/three-line-2d/index.html`

My browser outputs an error about missing bundle.js
1. Try `cd node_modules/three-line-2d/ ; npm run-script build`:

> Error: Cannot find module '/Users/peter/days/16_05_14/node_modules/three-line-2d/test/index.js' from '/Users/peter/days/16_05_14/node_modules/three-line-2d'

I don't know how to proceed from here.

If the answer is that I need to go read up on npm for a while, tell me and I'll buzz off. But I'd appreciate if this repo included the basic steps to get started!

**Comment by ridiculousfish** [comment]
(Also, in case there was any doubt, this looks really cool and I am desperate to try it!)

**Comment by mattdesl** [comment]
This module is intended to be consumed with npm and a bundler like Browserify. It may also work with Webpack, Rollup, etc – although I haven't tested those.

To run the demo for this project locally, you have to [clone and install dependencies](https://github.com/mattdesl/three-line-2d#running-from-source).

If you want to use it yourself from your project, you have a couple options. If you don't want to use npm/browserify/etc – you can download this module from a service like BrowserifyCDN or Wzrd.in. Here is a UMD build of the latest version, minified, which you can add into a `<script>` tag:
https://wzrd.in/standalone/three-line-2d@%5E1.1.3

The _recommended_ approach for all these modules is a bit more cumbersome, but IMHO generally worth it once you get over the initial learning curve. It involves npm, browserify, and a local development server like budo. The same concepts should transfer easily to Webpack, Rollup, etc. Further reading:
- [npm / modules for Frontend Devs](https://github.com/Jam3/jam3-lesson-module-basics)
- [Bare-bones browserify example](https://github.com/mattdesl/browserify-example)
- [Rapid Prototyping with Budo + Browserify](https://mattdesl.svbtle.com/rapid-prototyping)

The workflow is pretty much the same for all my modules (and lots of others – like stackgl), but the READMEs don't always include this sort of information.

Hope that clears things up! :tada:

P.S. Thanks for the heads up – I fixed some things in the readme.

**Comment by ridiculousfish** [comment]
Awesome! The readme update is a huge help and I got it running. Thank you so much!!
